# Host to use for canonical URL generation (without trailing slash)
host: https://content-api.publishing.service.gov.uk

# Header-related options
show_govuk_logo: false
service_name: GOV.UK Content API
service_link: https://content-api.publishing.service.gov.uk
phase: Work In Progress

# Links to show on right-hand-side of header
header_links:
  Home: index.html
  Technical Information: technical.html
  Reference: reference.html

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:

# Table of contents depth – how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 6

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false
